### ISSUE TITLE
Leetcode progress check

### ISSUE THREAD

**Issue by TracyDai23** [TracyDai23/Leetcode#1]
Leetcode progress check

**Comment by TracyDai23** [comment]
# Java Leetcode Progress

## Array
3 Read and remember how to use Hash map.
11 Self coded and bug free.
15 Not very easy to bug free. 1)Java List<List<Integer>> initialization and add; 2) tricky part to handle multiple combination. 
16 3Sum Done

8/13:
18 4Sum

**Comment by axd8911** [comment]
8/30: 
35. [Easy] Search Insert Position
33. [M] //To improve binary search algorithm
